### ISSUE TITLE
隨機出現的秒睡秒醒 , wake reason GLAN XDCI

### ISSUE THREAD

**Issue by Jamesxxx1997** [acai66/lenovo-miix-520-hackintosh-CLOVER#16]
樓主您好，想跟您請教一下
在我的這台miix-520當中，使用您的熱補丁會出現GLAN XDCI所造成的秒睡秒醒
![CleanShot 2019-08-23 at 18 49 34](https://user-images.githubusercontent.com/29252582/63587602-0429ce80-c5d7-11e9-9936-5e9ecfa120d5.png)
想請問一下應該如何修復呢？ 謝謝～

**Comment by acai66** [comment]
怎么复现这个，我这边没注意到过睡眠秒醒问题

**Comment by Jamesxxx1997** [comment]
睡眠秒醒問題好像是從以前就出現過，我和另一位有相同機型的黑友都有碰到相同的問題。
一般來說睡眠正常，但是會＂隨機出現＂GLAN XDCI的喚醒 ; 在這樣不正常的喚醒過後，就會出現GLAN XDCI的秒睡秒醒問題

能否請您做一個＂完全禁止usb鼠標喚醒＂的SSDT來讓我測試看看呢？
謝謝～

**Comment by acai66** [comment]
我看了我IORegistryExplorer里并没有出现xdci，你是不是插了typec扩展坞

**Comment by Jamesxxx1997** [comment]
您好，我是沒有插上type C擴展的，查找我的IOreg也沒有發現到xdci QAQ
[IORegistryExplorer.zip](https://github.com/acai66/lenovo-miix-520-hackintosh-CLOVER/files/3535468/IORegistryExplorer.zip)

**Comment by acai66** [comment]
我刚才试了下，睡眠时风扇停，电源灯一直在闪，等一段时间也没有自动唤醒，我手动按键盘唤醒的，发现日志里出现了Wake reason: GLAN XDCI，时间差不多是我按按键的时间，所以我感觉这个唤醒应该不是睡眠秒醒的

**Comment by Jamesxxx1997** [comment]
還是您能否發我一個完全禁止鼠標喚醒的SSDT讓我試試呢～ 感謝

**Comment by acai66** [comment]
替换clover/acpi/patched/下的试试。
[SSDT-GPRW.zip](https://github.com/acai66/lenovo-miix-520-hackintosh-CLOVER/files/3536794/SSDT-GPRW.zip)

**Comment by Jamesxxx1997** [comment]
好的感謝，我試試看～

**Comment by acai66** [comment]
如果还有异常设备导致的睡眠秒醒问题，请附带唤醒日志重新发issue，我将进一步修改hotpatch补丁

**Comment by Jamesxxx1997** [comment]
@acai66 您好，我的bios目前為6ncn39ww , 想請問一下如何降級bios呢？ 目前網上找不到6ncn35ww的bios檔案，謝謝

另外之前說的，GLAN XDCI所引起的睡眠問題也在這個bios版本中碰到了，想提交一下我的dsdt , 看您有無方法處理，謝謝
[origin.zip](https://github.com/acai66/lenovo-miix-520-hackintosh-CLOVER/files/4146530/origin.zip)
