### ISSUE TITLE
请问一下可外接显示器吗？

### ISSUE THREAD

**Issue by 22xiaogu** [acai66/lenovo-miix-520-hackintosh-CLOVER#17]
楼主您好，
有外接显示器的需求，请问这个黑苹果可以通过TypeC拓展坞外接显示器吗，是否有什么BUG之类？
                                                                                                                                                     感谢。

**Comment by acai66** [comment]
可以外接，要开机之后接

**Comment by 22xiaogu** [comment]
> 可以外接，要开机之后接

感谢！
然后还有另外一个问题就是，按您说的操作过了，但是睡眠唤醒以后还是不能用键盘。。不知咋回事。。
![image](https://user-images.githubusercontent.com/55054576/64973898-6af08e00-d8de-11e9-81c5-2712f38aa0cf.png)

**Comment by acai66** [comment]
> > 可以外接，要开机之后接
> 
> 感谢！
> 然后还有另外一个问题就是，按您说的操作过了，但是睡眠唤醒以后还是不能用键盘。。不知咋回事。。
> ![image](https://user-images.githubusercontent.com/55054576/64973898-6af08e00-d8de-11e9-81c5-2712f38aa0cf.png)

补丁包已更新，更新系统再用新补丁包试试
