### ISSUE TITLE
睡眠唤醒无效

### ISSUE THREAD

**Issue by TDwell520** [acai66/lenovo-miix-520-hackintosh-CLOVER#19]
![40A0D46F-A4F2-43C4-9771-AA7ECD30548C](https://user-images.githubusercontent.com/52964632/64870019-1a2a2c80-d675-11e9-98fe-329498ecfbb8.jpeg)
按照你的教程，都无法实现唤醒，求解哪一环节出错

**Comment by acai66** [comment]
睡眠唤醒应该没问题，这个是解决唤醒后键盘需要拔插才能用的bug的

**Comment by TDwell520** [comment]
> 睡眠唤醒应该没问题，这个是解决唤醒后键盘需要拔插才能用的错误的
嗯，是我说错了，唤醒后鼠标和键盘用不了

**Comment by freedomli1980** [comment]
我也是一样问题，安装了补丁没效果

**Comment by acai66** [comment]
[solution.zip](https://github.com/acai66/lenovo-miix-520-hackintosh-CLOVER/files/3666407/solution.zip)
试试这个，现在我的系统(10.15beta9)是没问题的.

**Comment by acai66** [comment]
已更新补丁包，更新系统，用新补丁包再试试
