### ISSUE TITLE
今天看视频时调整亮度发生的奇怪错误

### ISSUE THREAD

**Issue by danceking** [acai66/lenovo-miix-520-hackintosh-CLOVER#20]
今天油管看视频，调整了下亮度，视频上半部变黄了。。
真是很纳闷。
[http://132.232.28.83/IMG_20190921_215054.jpg](url)

**Comment by acai66** [comment]
没法恢复吗，感觉更像是系统bug

**Comment by danceking** [comment]
一会就恢复了，只是感觉第一次遇到，比较神奇。呵呵

再就是，休眠后键盘还是无法输入。

所有配置都是按照要求操作过。

**Comment by acai66** [comment]
https://github.com/acai66/lenovo-miix-520-hackintosh-CLOVER/issues/19#issuecomment-536255039
试试看

**Comment by danceking** [comment]
这个watch我已经安装了，patch也有，任务也在运行，但也是时好时坏。
补充下版本号：10.14.6 (18G103)
http://132.232.28.83/2019-09-30_9.30.34.png

**Comment by acai66** [comment]
编辑/usr/local/acai/patch，前面插入sleep 0.5
延迟0.5秒试试

**Comment by danceking** [comment]
已经添加，sleep 0.5
不重启情况下，无效果。
重启后，第一次睡眠有效，第二次开始就无效了。
