### ISSUE TITLE
Usb連到Ipad顯示未充電

### ISSUE THREAD

**Issue by Jamesxxx1997** [acai66/lenovo-miix-520-hackintosh-CLOVER#21]
不知道是不是我這個機子的問題，從usb type A
和usb type c dock，線接上ipad都會顯示未充電；iphone就是正常的
不知道有沒有人碰到相同的問題

**Comment by acai66** [comment]
之前的版本可以吗

**Comment by Jamesxxx1997** [comment]
QWQ我再測試看看～

**Comment by acai66** [comment]
> QWQ我再測試看看～

怎么样，上个版本我在hotpatch补丁里加入了ssdt-usbx补丁，以为能更加完美呢，你试试用与不用这个文件有没有变化

**Comment by acai66** [comment]
我昨天测试了一下，发现usb还是需要定制一下的，下个版本将完善usb信息的定制，目前在我的机器上可以为ipad充电了

**Comment by Jamesxxx1997** [comment]
太棒了～ 感謝～

**Comment by acai66** [comment]
已更新，修正了usb端口信息，修复了ipad充电问题

**Comment by Jamesxxx1997** [comment]
辛苦了～～～
