### ISSUE TITLE
bcm94352z如何驱动

### ISSUE THREAD

**Issue by MiChuancey** [acai66/lenovo-miix-520-hackintosh-CLOVER#23]
你好，我是远景过来的。不是同机型，但想请教bcm94352z蓝牙的问题。

下面我想说下我的问题：
蓝牙通过BrcmBluetoothInjector.kext驱动，能够正常开关，但经常搜不到信号。需要关机重启几次，或者进win开关蓝牙之类的操作后才能搜索到信号。

看到您的kext里面同时放了貌似冲突的驱动，见rehabman的[readme](https://github.com/RehabMan/OS-X-BrcmPatchRAM)
![image](https://user-images.githubusercontent.com/37216768/66923848-27637e00-f05c-11e9-9374-8405f84e1163.png)

能否讲下你是如何驱动蓝牙的，谢谢了

**Comment by acai66** [comment]
https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/你参考下这个吧，我目前蓝牙wifi都正常

**Comment by acai66** [comment]
https://github.com/acidanthera/BrcmPatchRAM
我用的蓝牙驱动源码来自于这里，多个版本之前作者就修复了macos10.15下不可用的问题，你可以试试不用那个injector

**Comment by acai66** [comment]
use new BrcmPatchRAM3.
