### ISSUE TITLE
请教一下仪表盘拖动部件花屏问题

### ISSUE THREAD

**Issue by caifenglin** [acai66/lenovo-miix-520-hackintosh-CLOVER#24]
你好，我的显卡是HD620，i5 7200U，安装10.14.6之后，仪表盘拖动部件一直花屏，显卡通过自动识别安装，请问对于水波纹花屏有什么好的建议吗，谢谢

**Comment by acai66** [comment]
仿冒6代u的核显id等，但可能会造成硬解问题，具体情况需要亲自尝试

**Comment by caifenglin** [comment]
我显卡就是HD620，不需要仿冒吧

**Comment by acai66** [comment]
仿冒hd520
