### ISSUE TITLE
touchscreen not working and wifi

### ISSUE THREAD

**Issue by kenshgo** [acai66/lenovo-miix-520-hackintosh-CLOVER#25]
Hi,

after following your instruction of deleting the appleIntelLpssI2C.kext and AppleIntelLpssI2CController.kext and run kext utility to rebuild your kextcache

my touch screen is still not working. also can you help me about my wifi adapter qualcom atheros qca61x4a its being detected by dpcimanager as QCA6174.

we have the same Lenovo Miix 520 but somewhat different spec. would appreciate your help thanks!

**Comment by acai66** [comment]
I guess you're using macos10.14.x,use voodooi2c.kext and voodooi2chid.kext
 from https://github.com/alexandred/VoodooI2C/releases

**Comment by acai66** [comment]
your wifi adapter may not work in macos,just replace with bcm94352z

**Comment by kenshgo** [comment]
@acai66 thanks will try this out. i just need to ask more question sorry as i am just new to hackintosh.
do i just mount the EFI folder from clover config and then drag the kexts to "clover/kext/other" folder or do i drag them to system/library/extensions?

**Comment by acai66** [comment]
clover/kexts/other

**Comment by kenshgo** [comment]
thank you so much for your help. i have another question hope you dont mind,
the SD reader how do i compile the kext by myself? and what bug do you experience?
do you think this will work?:https://www.lazada.com.ph/products/bcm94352z-wireless-ac-ngff-dual-band-80211ac-300m867mbps-wifi-bluetooth-bt-40-card-laptop-i283216389-s441032683.html

currently using a usb wifi dongle on my miix 520.

**Comment by acai66** [comment]
sd reader driver may cause hang on boot,
the wifi card form that link is an e key m.2 device,you need an a key wifi card,try search for 'dw1560'

**Comment by kenshgo** [comment]
where can i find the "E key" in that link that i posted?

**Comment by kenshgo** [comment]
would this work? https://www.lazada.com.ph/products/brand-new-dw1560-bcm94352z-06xryc-80211ac-ngff-m2-867mbps-bcm94352-bt40-wifi-wireless-network-cardnote-if-there-is-in-the-name-is-the-value-of-this-product-i294938016-s489464803.html?spm=a2o4l.searchlist.list.4.11223c92S8b4Nv&search=1

**Comment by acai66** [comment]
![1265175161__01](https://user-images.githubusercontent.com/37766207/68291959-e3492380-00c5-11ea-90c7-3ed17a716dba.jpg)
i found no bcm94352z in that stopping website like this with lenovo SN and two socket,you can try dw1560,and i'm not sure it can be recognized by miix 520

**Comment by kenshgo** [comment]
do you have a link where you bought yours? i am completely lost on how to check as there are alot of bcm94352z / DW1560 they all look the same. thank you!

**Comment by kenshgo** [comment]
how is catalina working out for you? do you encounter many more bugs?

**Comment by acai66** [comment]
no more bugs

**Comment by kenshgo** [comment]
do the multi gesture work in catalina?

**Comment by acai66** [comment]
yes,just like mojave,no more bugs

**Comment by kenshgo** [comment]
how did you fix the multi gesture? for my trackpad it doest work when i use 3 fingers to swipe up.

only 2 fingers work which is to use to scroll i really appreciate you helping me

**Comment by acai66** [comment]
trackpad works like a mouse, no multi gesture

**Comment by writzx** [comment]
> ![1265175161__01](https://user-images.githubusercontent.com/37766207/68291959-e3492380-00c5-11ea-90c7-3ed17a716dba.jpg)
> i found no bcm94352z in that stopping website like this with lenovo PN/FRU PN and two socket,you can try dw1560,and i'm not sure it can be recognized by miix 520

almost all the DW1560 sellers on AliExpress and ebay mention its not for lenovo. is it still worth a try even after that?

**Comment by kenshgo** [comment]
will any m2 nvme work if i upgrade to 1tb?

**Comment by acai66** [comment]
> > ![1265175161__01](https://user-images.githubusercontent.com/37766207/68291959-e3492380-00c5-11ea-90c7-3ed17a716dba.jpg)
> > i found no bcm94352z in that stopping website like this with lenovo PN/FRU PN and two socket,you can try dw1560,and i'm not sure it can be recognized by miix 520
> 
> almost all the DW1560 sellers on AliExpress and ebay mention its not for lenovo. is it still worth a try even after that?

you acn have a try

**Comment by acai66** [comment]
> will any m2 nvme work if i upgrade to 1tb?

i'm not srue but Samsung pm961 and Samsung pm981 work well

**Comment by writzx** [comment]
Well since we have a confirmation from a contributor himself i guess dw1560 should work.

https://www.reddit.com/r/hackintosh/comments/bol2pg/lenovo_miix520_hackintosh_tablet/enhia3c

**Comment by writzx** [comment]
Well since we have a confirmation from our translator himself i guess dw1560 should work.

https://www.reddit.com/r/hackintosh/comments/bol2pg/lenovo_miix520_hackintosh_tablet/enhia3c

**Comment by kenshgo** [comment]
do you have links where i can buy the network card? im currently in fei lu bin so its kinda hard to look for it here.

**Comment by kenshgo** [comment]
btw did you notice that the volume / loudness of the speaker decreased after installing mac os?

**Comment by writzx** [comment]
> do you have links where i can buy the network card? im currently in fei lu bin so its kinda hard to look for it here.

https://www.aliexpress.com/ has a lot of listings for dw1560. You should check if they are delivering there (probably they do).
