### ISSUE TITLE
替换新版本的文件后，卡在AppleACPICPU

### ISSUE THREAD

**Issue by lty2008one** [acai66/lenovo-miix-520-hackintosh-CLOVER#26]
会卡在busy timeout AppleACPICPU

**Comment by acai66** [comment]
全是用的新版吗

**Comment by lty2008one** [comment]
系统是10.14和10.15两个，都没法启动，用的是2.0的那个beta

**Comment by lty2008one** [comment]
切回1.8的版本可以正常启动10.15，但是10.14会在AppleSP2mouse那里卡很久，大概3～4分钟

**Comment by acai66** [comment]
> 切回1.8的版本可以正常启动10.15，但是10.14会在AppleSP2mouse那里卡很久，大概3～4分钟

我只有10.15，测试没问题的

**Comment by acai66** [comment]
你是用的clover吗

**Comment by acai66** [comment]
如果还有这个问题，请重开issue
