### ISSUE TITLE
您好，我经过尝试后百分之90驱动了我的miix510-121sk，还有些问题想向您请教

### ISSUE THREAD

**Issue by onnonn** [acai66/lenovo-miix-520-hackintosh-CLOVER#31]
1.只要将显卡id改为19160000，声卡id修改为28即可，电源与休眠无需修改直接完美，触屏也完美，我可以引用您的配置来发布miix510的配置吗
2.我用的网卡是DW1820A 00JT494（联想版），wifi不用屏蔽针脚可驱动，但是蓝牙无法连接（表现为可搜索设备，连接后瞬间断连，且另一台设备没有任何连接成功的提示），这个是需要注入解决还是修改dsdt呢？
3.触控板在设置中能修改手势设置，但是触控板只能点按，触控板双指方向只朝向一个方向，这个需要修改哪里呢？
4.偶尔还是需要重新插拔键盘来唤醒键盘
5.dsdt与注入的区别是啥呢，哪些问题是可以通过dsdt解决的呢？

**Comment by acai66** [comment]
可以发布，注明来源。我是用的蓝牙驱动是附带绝大多数固件的通用驱动，你这个蓝牙还是有问题的话，就可能与硬件有关了。触摸板设置里的那个是触屏，这平板键盘上的触摸板在mac下目前只能像鼠标一样工作。唤醒键盘失效在我这边没再出现过，不清楚你那边什么原因。动态注入补丁更完美些，通用型也好

**Comment by onnonn** [comment]
谢谢大师傅解答，我今天调试又发现了一个问题，不知道您那边有没有出现，就是VoodooI2CHID.kext驱动触屏实现触控板手势的时候，存在触摸与触控板混合的问题，比如三指查词时指针会跳动，双指滑动时指针处于两指之间，能不能通过什么方发来让触屏实现纯触控板的功能呢？

**Comment by Jamesxxx1997** [comment]
> VoodooI2CHID.kext驱动触屏实现触控板手势的时候，存在触摸与触控板混合的问题，比如三指查词时指针会跳动，双指滑动时指针处于两指之间，能不能通过什么方发来让触屏实现纯触控板的功能呢？

無法，voodooi2c驅動的觸屏就是這樣子的
