### ISSUE TITLE
启动热键不能使用

### ISSUE THREAD

**Issue by wdrich** [acai66/lenovo-miix-520-hackintosh-CLOVER#37]
您好  我使用来2.2版本的IOPENCORE引导 不能使用开机热键功能？

**Comment by acai66** [comment]
等支持热键的GUI opencore主题出来，现在我用的是opencore官方推荐的一个gui主题，目前发现热键失效，不过这个主题支持触屏，还算是挺方便的

**Comment by acai66** [comment]
已更新v2.4，opencore的图形引导界面支持热键
