### ISSUE TITLE
2.3版本不能启动WIN10

### ISSUE THREAD

**Issue by wdrich** [acai66/lenovo-miix-520-hackintosh-CLOVER#38]
你好 更新2.3版本的CLOVER引导WIN10的时候卡住，然后就重启了！不知道您有没有遇到

**Comment by ruiwei687** [comment]
我也有这样的问题

**Comment by acai66** [comment]
好像是忘记屏蔽掉clover/acpi/windows下的dsdt了，下次版本更新时修复

**Comment by lz00qs** [comment]
等一波更新

**Comment by acai66** [comment]
已更新v2.4，亲测opencore和clover均可引导macOS和Windows
